version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=platzi-store-users
      - POSTGRES_USER=platzerito
      - POSTGRES_PASSWORD=nuncaparesdeaprender
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
